In [10]:
import random

In [11]:
import numpy as np

a= np.array([[1,3,4],[3,4,5]])
print(a, a.ndim)
print(a.shape[1])

[[1 3 4]
 [3 4 5]] 2
3


Array declaration and Reshaping

In [12]:
a=[1,2,3,4,5,6]
npA= np.array(a)
npA

npB = npA.reshape(2,3)
print(npB)

[[1 2 3]
 [4 5 6]]


Array linspace function

In [13]:
a= np.linspace(1,10,30)
a

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

Array arange and reshape

In [14]:
a= np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Array Operations

In [15]:
a= np.array([1,2,3,4])
b= np.array([2,3,4,5])
print (a+b)
print (a-b)
print(a+20)
a*=3
print(a)

[3 5 7 9]
[-1 -1 -1 -1]
[21 22 23 24]
[ 3  6  9 12]


In [16]:
c= np.arange(9).reshape(3,3)
c*=10
print('The original array\n',c)

cRowSum=c.sum(axis=1)
print('Row Sum',cRowSum)

cColSum=c.sum(axis=0)
print('Col sum',cColSum)


The original array
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Row Sum [ 30 120 210]
Col sum [ 90 120 150]


In [17]:
list_1 =  [[1,3],[2,5],[1,2],[1,0],[2,10]]
arr= np.array(list_1)
print(arr)

print(arr.shape)

ar= np.where(arr[:,0]==1, arr[:,1], int(-1))
print(ar)

ar=ar[ar!=-1]
print(ar)

mean1= np.mean(ar)
print(mean1)


[[ 1  3]
 [ 2  5]
 [ 1  2]
 [ 1  0]
 [ 2 10]]
(5, 2)
[ 3 -1  2  0 -1]
[3 2 0]
1.6666666666666667


In [26]:
arr = np.random.randint(0,8,(2,3))
print(arr)

checked= np.where(arr%2!=0 , 'no', 'yes')
print(checked)

[[2 3 3]
 [0 4 4]]
[['yes' 'no' 'no']
 ['yes' 'yes' 'yes']]


In [30]:
arr = np.random.randint(2,9, 5)
print(arr)

rev= np.flip(arr)
print(rev)


[6 5 4 6 6]
[6 6 4 5 6]
